### PR TITLE
Add assign command

### PR DESCRIPTION
**Pull request by alphajae11**
Add assign command as a part of v1.2

Adhere to code standards

### CODE REVIEW

**Comment by Fidget-Spinner** [comment]
Run `./gradlew check coverage` on your computer instead of constantly pushing and checking.

**Review by LifHoshi — APPROVED** [review]
No errors about name conventions and format

**Review by JuliaPoo — APPROVED** [review]

**Review by LifHoshi — APPROVED** [review]
No errors about naming and format of file

**Comment by alphajae11** [comment]
image

Added assign command to assign members with a role

**Review by Fidget-Spinner — APPROVED** [review]

**Comment by Fidget-Spinner** [comment]
For posterity, this line needs updating with CCA https://github.com/AY2324S2-CS2103T-W11-2/tp/pull/45/files#diff-848908bc8f9ed2cc3550acecba738a94373ab62f74cc4530a078820d58341862R97 after JJ's commit.

**Comment by alphajae11** [comment]
Closes #2

**Pull request merged**
