### PR TITLE
Change `r/` and `c/` as a way to clear the fields to `r/nil` and `c/nil`

### LINKED ISSUE #149: [PE-D][Tester A] edit cca with only whitespace
<i><video controls><source src="https://raw.githubusercontent.com/Bandov/ped/main/files/7d96a994-e86f-4702-8af1-74be252e92fc.mov" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/Bandov/ped/main/files/7d96a994-e86f-4702-8af1-74be252e92fc.mov</i>
Steps to reproduce:
see video
Expected:
Error showing that the club name does not exist or having a club with a blank name in the clubs section
Actual:
It shows to the user that the person has been updated instead of throwing an error.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Bandov/ped#7

### LINKED ISSUE #185: Currently no way to clear roles and CCAs for a member
Related #149

### PR DESCRIPTION
**Pull request by JuliaPoo**
Fixes #149, Fixes #185.

### CODE REVIEW

**Comment by Fidget-Spinner** [comment]
What happens when you pass this as a role to another command? e.g. the charge command?

**Comment by JuliaPoo** [comment]
It errors out with invalid role format, since I added the check within the Role.isValid thingy

**Comment by Fidget-Spinner** [comment]
Ok needs merge conflict fixing/

**Comment by JuliaPoo** [comment]
Okay I did the merge.

**Review by Fidget-Spinner — APPROVED** [review]

**Pull request merged**
